// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MidTerm8897.Models;

#nullable disable

namespace MidTerm8897.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MidTerm8897.Models.Appointments", b =>
                {
                    b.Property<int>("id_appointment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_appointment"));

                    b.Property<DateTime>("appointment_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_doctor")
                        .HasColumnType("int");

                    b.Property<int>("id_patient")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_appointment");

                    b.HasIndex("id_doctor");

                    b.HasIndex("id_patient");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MidTerm8897.Models.Doctors", b =>
                {
                    b.Property<int>("id_doctor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_doctor"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("work_experience")
                        .HasColumnType("int");

                    b.HasKey("id_doctor");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("MidTerm8897.Models.MedicalRecords", b =>
                {
                    b.Property<int>("id_medical_record")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_medical_record"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_appointment")
                        .HasColumnType("int");

                    b.Property<int>("id_doctor")
                        .HasColumnType("int");

                    b.Property<int>("id_patient")
                        .HasColumnType("int");

                    b.Property<string>("treatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_medical_record");

                    b.HasIndex("id_appointment")
                        .IsUnique();

                    b.HasIndex("id_doctor");

                    b.HasIndex("id_patient");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("MidTerm8897.Models.Patients", b =>
                {
                    b.Property<int>("id_patient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_patient"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_patient");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MidTerm8897.Models.Appointments", b =>
                {
                    b.HasOne("MidTerm8897.Models.Doctors", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("id_doctor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MidTerm8897.Models.Patients", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("id_patient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MidTerm8897.Models.MedicalRecords", b =>
                {
                    b.HasOne("MidTerm8897.Models.Appointments", "Appointment")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("MidTerm8897.Models.MedicalRecords", "id_appointment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MidTerm8897.Models.Doctors", "Doctor")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("id_doctor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MidTerm8897.Models.Patients", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("id_patient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MidTerm8897.Models.Appointments", b =>
                {
                    b.Navigation("MedicalRecord")
                        .IsRequired();
                });

            modelBuilder.Entity("MidTerm8897.Models.Doctors", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("MidTerm8897.Models.Patients", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
